[project]
name = "2024-pypi-stats"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.0",
    "pandas>=2.2.3",
    "pytest>=8.3.4",
    "ruff>=0.8.4",
    "seaborn>=0.13.2",
    "wlc>=1.15",
]
